### ISSUE TITLE
Missing function to set WPM (Morse::gpio_set_wpm)

### ISSUE THREAD

**Issue by om0wt** [basepr1me/Morse#1]
Hi Tracey,
Thanks a lot for this nice piece of code, I like a lot!

I'm developing a simple ESP32 based CW beacon:

<img width="673" alt="Screenshot 2023-01-08 at 23 58 01" src="https://user-images.githubusercontent.com/122154544/211223335-151eac2e-0ef4-4767-b450-6de191b62369.png">

Your library just fits perfectly for this purpose. I've been missing only a function to change the WPM anytime I want. I added one that works for me:

```c++
Morse::gpio_set_wpm(uint8_t the_wpm) {
 			gpio_wpm = the_wpm;
 			gpio_unit_t = UNIT_T(gpio_wpm);
 			gpio_inited = 1;
 }
 ```

Thanks again also for RPI Pico version of it... 

VY 73 AND HNY de Pavol OM0WT

**Comment by basepr1me** [comment]
Thank you. Makes sense to add this. Happy to add your code with a PR.

**Comment by basepr1me** [comment]
Code merged. Thanks!
